# Generated by Django 5.2.10 on 2026-01-17 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_study', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='studysession',
            name='unique_active_session_per_user',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='created_at',
        ),
        migrations.AddField(
            model_name='subject',
            name='color',
            field=models.CharField(default='#0e7490', max_length=7),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subject',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='studysession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('user',), name='one_active_session_per_user'),
        ),
    ]
