# Generated by Django 5.2.10 on 2026-01-18 03:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_study', '0003_subject_created_at_alter_subject_color_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studysession',
            options={'ordering': ['-start_time']},
        ),
        migrations.RemoveConstraint(
            model_name='studysession',
            name='one_active_session_per_user',
        ),
        migrations.AddField(
            model_name='studysession',
            name='group_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps_study.grouproom'),
        ),
        migrations.AddField(
            model_name='studysession',
            name='session_type',
            field=models.CharField(choices=[('solo', 'Solo'), ('group', 'Group')], default='solo', max_length=10),
        ),
        migrations.AlterField(
            model_name='grouproom',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='grouproom',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='status',
            field=models.CharField(default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps_study.subject'),
        ),
    ]
