# Generated by Django 5.2.10 on 2026-01-18 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_study', '0004_alter_studysession_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysession',
            name='color_snapshot',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='studysession',
            name='name_snapshot',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
