# Generated by Django 5.2.10 on 2026-01-19 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_study', '0005_studysession_color_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='progress',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='weekly_goal',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
