# Generated by Django 5.2.10 on 2026-01-19 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_study', '0007_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysession',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='apps_study.task'),
        ),
    ]
