# Generated by Django 5.2.10 on 2026-01-19 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_study', '0008_studysession_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='actual_duration',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
